### ISSUE TITLE
🐛After Docker deployement, when register "An unexpected error occurred..."

### ISSUE THREAD

**Issue by vfbfreeman** [HiEventsDev/Hi.Events#336]
Hello,

I have followed this deployement guide "https://github.com/HiEventsDev/Hi.Events/tree/develop/docker/all-in-one".
No problem.... Containers have been created ans run.
 I'm going to the register page, put my informations, and afer i'm clicking on register : 

<img width="799" alt="image" src="https://github.com/user-attachments/assets/566a38e6-2245-4ad1-9fcc-8322af539c52" />

Any ideas ?

OS : Linux (ubuntu 24.04)

No firewall restriction.

**Comment by daveearley** [comment]
Hi @vfbfreeman,

Can you see any errors in the frontend/backend container logs, or the browser console?

**Comment by dOcSeRFi** [comment]
Hi.

I had the exact same issue. The all-in-one docker image, and .env is setup to use only port 80 (http) inside the container. And the API gives CORS error. And status code 500.

So the only way the all-in-one will work is to run it via a domain with https, or if you have a local nameserver with ssl/https support. Here is a copy of the .env file I managed to get to work:.(The actual domain-name has been redacted, and replaced with example.com. The rest is same).     
<br/>

> The exact console error is this:  
~~~
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.69.174:8123/api/auth/register (Reason: CORS request did not succeed). Status code: (null).
~~~
<br/>
<br/>

> ## .env file for Hi.Events all-in-one docker image. 
~~~
# See the README.md file for informaiton on how to generate the JWT_SECRET and APP_KEY
APP_KEY=base64:puOJbTaB8SEC3vVRPfnXDGhz99wnEiTTPtgv1X073Hw=
JWT_SECRET=TaZ09mQ5AiJNHRweIB4r4kTIdmlNBGndRKgRHr9nZ7o=

# Frontend variables (Always prefixed with VITE_)
VITE_FRONTEND_URL=https://test.docserfi.no
VITE_API_URL_CLIENT=https://test.docserfi.no/api
VITE_API_URL_SERVER=http://localhost:8000/api
VITE_STRIPE_PUBLISHABLE_KEY=pk_test

# Backend variables
# These values may not be suitable for production environments.
# Please refer to the documentation for more information on how to configure these values
# https://hi.events/docs/getting-started/deploying
LOG_CHANNEL=stderr
QUEUE_CONNECTION=sync
MAIL_MAILER=log

FILESYSTEM_PUBLIC_DISK=public
FILESYSTEM_PRIVATE_DISK=local

APP_CDN_URL=https://test.docserfi.no/storage
APP_FRONTEND_URL=https://test.docserfi.no

DATABASE_URL=postgresql://postgres:secret@postgres:5432/hi-events
~~~

**Comment by vfbfreeman** [comment]
I followed your instructions.... But unfortunately it didn't work.
I still have the same problem.
Good... I think I'll test another solution.

**Comment by Shtooth** [comment]
I'm experiencing the same issue on a fresh install.  
I think there is a redirection somewhere to port 80 that might be causing the problem.

![image](https://github.com/user-attachments/assets/f093178e-44ff-4e89-8c86-f81f5d906384)

**Comment by dOcSeRFi** [comment]
@daveearley 
Have you been able to look in to this? :)

**Comment by daveearley** [comment]
Hi @dOcSeRFi,

I looked into this, but I wasn’t able to reproduce the issue. For context, I’ve only been testing the default local setup on localhost, and it works as expected on my end.

That said, I’m stretched pretty thin at the moment, so I haven’t had much time to debug setups that differ from the standard Mac environment using localhost.

If you could provide more detail, such as your OS, whether you’re using a local IP or localhost, how you’re starting the containers, etc., it would help me get more context and hopefully reproduce the issue.

Also, if anyone else has encountered similar issues and found a fix, please feel share it here :-) 

Thanks!

**Comment by Shtooth** [comment]
> Hi @dOcSeRFi,
> 
> I looked into this, but I wasn’t able to reproduce the issue. For context, I’ve only been testing the default local setup on localhost, and it works as expected on my end.
> 
> That said, I’m stretched pretty thin at the moment, so I haven’t had much time to debug setups that differ from the standard Mac environment using localhost.
> 
> If you could provide more detail, such as your OS, whether you’re using a local IP or localhost, how you’re starting the containers, etc., it would help me get more context and hopefully reproduce the issue.
> 
> Also, if anyone else has encountered similar issues and found a fix, please feel share it here :-)
> 
> Thanks!

Hello Dave.

I have taken another look and the redirection that I was observing was a different service on my side and it was originated as the .env file in all-in-one folder lists the following

```
VITE_FRONTEND_URL=http://localhost:8123
VITE_API_URL_CLIENT=http://localhost:8123/api
VITE_API_URL_SERVER=http://localhost:80/api
```

And it might cause some confusion as by changing port 80 to 8123 I was able to reach the appropriate service (Probably worth it to update the .env file there to avoid further spam of this). 

I still think there is a bug in the registration as I noticed that the latest release and the current development code contain a hidden timezone field that seems to be causing some problems during the registration it generates the following logs

```
all-in-one  | [2025-01-11 20:12:13] production.WARNING: Unexpected timezone received: Etc/GMT+6
all-in-one  | 192.168.50.231 - - [11/Jan/2025:20:12:13 +0000] "POST /api/auth/register HTTP/1.1" 422 140 "http://192.168.100.2:8123/auth/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"
all-in-one  | 127.0.0.1 -  11/Jan/2025:20:12:13 +0000 "POST /index.php/auth/register" 422
```
![image](https://github.com/user-attachments/assets/adffc458-d0cf-4646-9c08-a2afa618247d)


If I replicate the connection and remove the timezone value from it the registration works as expected.

Hope this help more than  my previous message

**Comment by rollemira** [comment]
I'm getting the same:
```
10.0.1.8 - - [28/Jan/2025:04:57:56 +0000] "POST /api/auth/register HTTP/1.1" 500 44 "https://example.com/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
```
This is coming from a dokploy setup using the latest all-in-one image

**Comment by rollemira** [comment]
> I'm getting the same:
> 
> ```
> 10.0.1.8 - - [28/Jan/2025:04:57:56 +0000] "POST /api/auth/register HTTP/1.1" 500 44 "https://example.com/auth/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
> ```
> 
> This is coming from a dokploy setup using the latest all-in-one image

After some tweaking I was able to get this to run on a dokploy server. It _should_ work for coolify too if that's what somebody else is using.

**docker-compose**
```
services:
  all-in-one:
    image: daveearley/hi.events-all-in-one:latest
    restart: always
    environment:
      - VITE_FRONTEND_URL=https://${DOMAIN}
      - APP_FRONTEND_URL=https://${DOMAIN}
      - VITE_API_URL_CLIENT=https://${DOMAIN}/api
      - VITE_API_URL_SERVER=http://localhost:8080/api
      - VITE_STRIPE_PUBLISHABLE_KEY
      - LOG_CHANNEL=stderr
      - QUEUE_CONNECTION=sync
      - APP_KEY
      - JWT_SECRET
      - FILESYSTEM_PUBLIC_DISK=public
      - FILESYSTEM_PRIVATE_DISK=local
      - APP_CDN_URL=https://${DOMAIN}/storage
      - APP_DISABLE_REGISTRATION
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - STRIPE_PUBLIC_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME
    depends_on:
      - postgres

  postgres:
    image: elestio/postgres:16
    restart: always
    networks:
      - dokploy-network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - hi_events_data:/var/lib/postgresql/data

networks:
  dokploy-network:
    external: true

volumes:
  hi_events_data:
```
**env**
```
# change domain here
DOMAIN=example.com

POSTGRES_DB=hievents
POSTGRES_USER=hievents
POSTGRES_PASSWORD=supersecretpassword

VITE_STRIPE_PUBLISHABLE_KEY=<your_public_key>

APP_KEY=base64:<your_secret>
JWT_SECRET=<your_secret>

APP_DISABLE_REGISTRATION=false

STRIPE_PUBLIC_KEY=<your_public_key>
STRIPE_SECRET_KEY=<your_secret_key>
STRIPE_WEBHOOK_SECRET=<your_secret>

MAIL_MAILER=log
MAIL_HOST=
MAIL_PORT=
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=
```
